FROM python:3.11

# Instala Tesseract OCR
RUN apt-get update && apt-get install -y tesseract-ocr

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos para dentro da imagem
COPY . /app

# Instala as dependências do projeto
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expõe a porta padrão do Streamlit
EXPOSE 8501

# Comando que será executado ao iniciar o container
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
